services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/ssl:ro  # Mount your SSL certificates here
    depends_on:
      - oauth2-proxy
      - webhosting
    networks:
      - frontend
      - backend

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    volumes:
      - ./oauth2-proxy.conf:/etc/oauth2-proxy/oauth2-proxy.conf
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${GITHUB_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
    command:
      - --email-domain=*
    ports:
      - "4180:4180"
    networks:
      - frontend
      - backend

  webhosting:
    build: ./webhosting
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./web-root:/web-root

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
